apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonebld1514
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonebld1514
    app.kubernetes.io/part-of: stonebld1514
  name: stonebld1514zg0n
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: stonebld1514
    weight: null
status: {}
