apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonebld1514
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonebld1514
    app.kubernetes.io/part-of: stonebld1514
  name: stonebld1514
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: stonebld1514
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: stonebld1514
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ncross-tenant/stonebld1514/stonebld1514@sha256:fb1612d74ed69ff80e5486f5fb48e81305458f7fe6c2b16681ba8f6e5d8ef5fe
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
